dist: trusty

cache: apt

addons:
  chrome: stable
  apt:
    packages:
      - imagemagick
      - python
before_script:
    - python -m SimpleHTTPServer 8000 &
script:
    - google-chrome-stable --headless --disable-gpu --hide-scrollbars --screenshot --window-size=1280,1696 http://localhost:8000/index.html
    - identify -verbose -features 1 -unique screenshot.png
    - identify -verbose -features 1 -unique screenshot.png | grep -A 1 Histogram > histogram.txt
    - cat histogram.txt
    - grep -q '(255,255,255,255) #FFFFFF white' histogram.txt
